name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    # Build for messenger-client
    steps:
    - uses: actions/checkout@v3
    - uses: SarweshKumarTiwari/Messenger@v3
      id: filter
      with:
        filters: |
          client:
            - 'client/**'
          server:
            - 'server/**'
    
    - name: Build the Docker image for messenger client 
      working-directory: ./client
      if: steps.filter.outputs.client=='true'
      run: docker build -t sarweshkumartiwari/messenger-client:0.0.${{github.run_number}}
      
    - name: Build the docker image for messenger-server
      working-directory: ./server
      if: steps.filter.outputs.server=='true'
      run: docker build -t sarweshkumartiwari/messenger-server:0.0.${{github.run_number}}
      